name: githubaction2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  jobs1:
    runs-on: ubuntu-latest
    steps:
      - name: printhello
        run: echo "hello world"

  jobs2: 
    runs-on: ubuntu-latest
    needs: jobs1
    steps:
      - name: envandsecrets
        run: echo "Using env and secret"
        env: 
          name: "chiku" 
          password: ${{ secrets.MY_PASS }}

  jobs3:
    runs-on: ubuntu-latest
    needs: jobs2
    steps:
      - name: file
        run: echo "chiku" > first.txt
    
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: upload
          path: first.txt

  jobs4: 
    runs-on: ubuntu-latest
    needs: jobs3
    steps:
      - name: download
        uses: actions/download-artifact@v4
        with:
          name: upload   # must match upload name from jobs3

      - name: show file
        run: cat first.txt

      - name: output
        run: echo "output"

     
